# Generated by Django 4.2.6 on 2023-11-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.CharField(default=1234567890, max_length=10, verbose_name='TELEGRAM_CHAT_ID'),
            preserve_default=False,
        ),
    ]
