# Generated by Django 4.2.6 on 2023-10-30 21:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время выполнения')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('period', models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five'), ('six', 'Six'), ('daily', 'Daily')], default='daily', max_length=9, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=50, null=True, verbose_name='вознаграждение')),
                ('time_performance', models.IntegerField(default=120, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(0)], verbose_name='время на выполнение')),
                ('is_pablish', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atomic_habits.habit', verbose_name='связанная привычка')),
            ],
        ),
    ]
